[tool.poetry]
name = "my_fastapi"
version = "0.1.0"
description = ""
authors = ["luiscore200"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = {extras = ["standard"], version = "^0.34.3"}
langchain = "^0.3.25"
numpy = "^2.3.0"
transformers = "^4.52.4"
fastapi = "0.115.9"
chromadb = "^1.0.12"
langchain-community = "^0.3.25"
python-dotenv = "^1.1.0"
python-multipart = "^0.0.20"
groq = "^0.28.0"
aiosqlite = "^0.21.0"
google-generativeai = "^0.8.5"
langchain-openai = "^0.3.24"
langchain-groq = "^0.3.2"
pandas = "^2.3.0"
anyio = "^4.9.0"
sentence-transformers = "^4.1.0"
langchain-huggingface = "^0.3.0"
qdrant-client = "^1.14.3"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
